name: Build APK with Optional Profile

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      profile:
        description: "Buildozer profile (default or demo)"
        required: false
        default: "default"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v3

      - name: 🐍 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: ☕ Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: "17"

      - name: 📦 Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip curl git build-essential \
            libffi-dev libssl-dev libsqlite3-dev zlib1g-dev

      - name: 🛠️ Run build.sh with profile input
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            PROFILE="${{ github.event.inputs.profile }}"
          else
            PROFILE="default"
          fi
          echo "📂 Using profile: $PROFILE"
          ./build.sh "$PROFILE"
      
      - name: 📄 Upload Build Log
        uses: actions/upload-artifact@v4
        with:
          name: buildozer-log
          path: buildozer.log

      - name: 📤 Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ErudaBrowser-${{ github.event.inputs.profile || 'default' }}
          path: bin/*.apk
